baseURL = "https://riochndr.github.io/"
languageCode = "en-us"
title = "Stay Curious Blog | Rio Chandra"
theme = "PaperMod"
disqusShortname = 'kenichi-1'
googleAnalytics = 'G-FW43VY3B4Q'

[params.homeInfoParams]
Title = "Stay Curious. Stay Positive"
Content = "My blog to share anything. [About writer](/about/)"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/riochndr726/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/RioChndr"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/rio_chndr"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/rio_chndr/"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowBreadCrumbs = true
comments = true